[package]
name = "zte"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
slotmap = "1.0"
crossterm = "0.27"
thiserror = "1.0"
chumsky = { version = "0.10.1", features = ["pratt"] }
unicode-display-width = "0.3.0"
clipboard = "0.5.0"

[profile.dev]
opt-level = 2
